spring:
  application:
    name: ggauth

server:
  port: 8080

app:
  version: ${SERVER_VERSION:development}
  auth:
    key: ${SINGING_KEY:a1b2c3d4e5f6g7h8i9j0k1l2m3n4o5p6}
    issuer: GGAUTH
    access-token-expiration-minutes: 60
    refresh-token-expiration-minutes: 10080 #a week

management:
  observations:
    annotations:
      enabled: true
  metrics:
    distribution:
      percentiles-histogram:
        http.server.requests: true
      percentiles:
        http.server.requests: 0.5, 0.95, 0.99
    tags:
      application: ggauth
    enable:
      all: true
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
